from src.common.base_repository import BaseDocument

class SourceAssetModel(BaseDocument):
    """
    Represents a user-uploaded asset in the Firestore database.
    The document ID is auto-generated by Firestore.
    """
    user_id: str  # Firebase Auth UID of the owner
    gcs_uri: str
    original_filename: str
    mime_type: str
    file_hash: str  # SHA-256 hash of the original file for de-duplication
