import {Template, MimeType, IndustryEnum} from './template.model';

const localPath = 'assets/media_templates/';

// A hardcoded list of templates for demonstration purposes
export const TEMPLATES: Template[] = [
  {
    id: 'rolex-local',
    name: 'Rolex Showcase',
    description: 'A showcase of Rolex video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.LUXURY_GOODS,
    brand: 'Rolex',
    tags: ['luxury', 'watch', 'elegant'],
    thumbnailUris: [],
    presignedUrls: [
      `${localPath}rolex_1_template.mp4`,
      `${localPath}rolex_2_template.mp4`,
    ],
    generationParameters: {
      prompt:
        'In a sleek black studio, the golden Rolex crown and logo appear with a metallic glint, accompanied by a deep, mechanical ticking. The logo then deconstructs, its letters unfolding into a cloud of tiny, elegant watch components like gears, springs, and bezels that float in slow motion. With magnetic precision, these individual particular isolated parts begin to snap together, to assemble each other with great precision, assembling the intricate internal mechanism first, followed by the dial, case, and bracelet, all with satisfying high-end clicks. Finally, the fully assembled Rolex watch floats in the studio light, its polished surfaces reflecting the light as the camera does a final, slow orbit to reveal the finished timepiece. The cyclops lens should mark 28. The watch should only have the word "Rolex" written inside of it, no subtitle nor mantra.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: 'Modern',
      lighting: 'Cinematic',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt:
        'no human hands or interaction, no imperfections, no cartoonish visuals',
      numMedia: 2,
      durationSeconds: 5,
    },
  },
  {
    id: 'dyson-local',
    name: 'Dyson Technology',
    description: 'A showcase of Dyson video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.HOME_APPLIANCES,
    brand: 'Dyson',
    tags: ['technology', 'vacuum', 'innovative'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}dyson_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Dyson.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'apple-local',
    name: 'Apple Products',
    description: 'A showcase of Apple video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.TECHNOLOGY,
    brand: 'Apple',
    tags: ['tech', 'iphone', 'macbook'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}apple_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Apple.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'ikea-local',
    name: 'IKEA Home',
    description: 'A showcase of IKEA video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.HOME_APPLIANCES,
    brand: 'IKEA',
    tags: ['furniture', 'home', 'scandinavian'],
    thumbnailUris: [],
    presignedUrls: [
      `${localPath}ikea_1_template.mp4`,
      `${localPath}cymball_ikea_1_template.mp4`,
    ],
    generationParameters: {
      prompt: 'A generated video for IKEA.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'maserati-local',
    name: 'Maserati Drive',
    description: 'A showcase of Maserati video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.AUTOMOTIVE,
    brand: 'Maserati',
    tags: ['luxury car', 'sports car', 'italian'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}maserati_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Maserati.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'jeep-local',
    name: 'Jeep Adventure',
    description: 'A showcase of Jeep video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.AUTOMOTIVE,
    brand: 'Jeep',
    tags: ['off-road', 'adventure', '4x4'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}jeep_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Jeep.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'tesla-local',
    name: 'Tesla Electric',
    description: 'A showcase of Tesla video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.AUTOMOTIVE,
    brand: 'Tesla',
    tags: ['electric car', 'ev', 'sustainable'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}tesla_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Tesla.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'chewy-local',
    name: 'Chewy Pets',
    description: 'A showcase of Chewy video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.PET_SUPPLIES,
    brand: 'Chewy',
    tags: ['pets', 'dogs', 'cats'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}chewy_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Chewy.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'lv-local',
    name: 'Louis Vuitton Style',
    description: 'A showcase of Louis Vuitton video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.LUXURY_GOODS,
    brand: 'Louis Vuitton',
    tags: ['fashion', 'luxury', 'handbag'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}lv_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Louis Vuitton.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'corona-local',
    name: 'Corona Beach',
    description: 'A showcase of Corona video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.FOOD_AND_BEVERAGE,
    brand: 'Corona',
    tags: ['beer', 'beach', 'summer'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}corona_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Corona.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'snickers-local',
    name: 'Snickers Break',
    description: 'A showcase of Snickers video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.FOOD_AND_BEVERAGE,
    brand: 'Snickers',
    tags: ['chocolate', 'snack', 'hungry'],
    thumbnailUris: [],
    presignedUrls: [`${localPath}snickers_1_template.mp4`],
    generationParameters: {
      prompt: 'A generated video for Snickers.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'mandms-local',
    name: "M&M's Fun",
    description: "A showcase of M&M's video templates.",
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.FOOD_AND_BEVERAGE,
    brand: "M&M's",
    tags: ['candy', 'colorful', 'fun'],
    thumbnailUris: [],
    presignedUrls: [
      `${localPath}mym_1_template.mp4`,
      `${localPath}mym_2_template.mp4`,
    ],
    generationParameters: {
      prompt: "A generated video for M&M's.",
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'whiskas-local',
    name: 'Whiskas Cats',
    description: 'A showcase of Whiskas video templates.',
    mimeType: MimeType.VIDEO,
    industry: IndustryEnum.PET_SUPPLIES,
    brand: 'Whiskas',
    tags: ['cat food', 'pets', 'feline'],
    thumbnailUris: [],
    presignedUrls: [
      `${localPath}whiskas_1_template.mp4`,
      `${localPath}whiskas_2_template.mp4`,
    ],
    generationParameters: {
      prompt: 'A generated video for Whiskas.',
      model: 'veo-3.0-generate-preview',
      aspectRatio: '16:9',
      style: '',
      lighting: '',
      colorAndTone: '',
      composition: '',
      negativePrompt: '',
    },
  },
  {
    id: 'google-illustration-style',
    name: 'Google Illustration Style',
    description:
      'A simple vector illustration with a light blue atmosphere and colorful characters, perfect for modern websites.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.TECHNOLOGY,
    brand: 'Google',
    tags: ['google style', 'vector', 'illustration', 'website graphics'],
    presignedUrls: [`${localPath}google-illustration-style_template.png`],
    generationParameters: {
      prompt:
        'A simple vector illustration on a white background with light blue background atmosphere and colorful characters. It features [subject in location]. A google-style vector illustration. The type of illustration you would see on a modern website.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '16:9',
      style: 'Modern',
      lighting: 'Natural',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: 'photorealistic, 3d, shadows',
      numMedia: 4,
    },
  },
  {
    id: '3d-clay-stickers',
    name: '3D Clay Stickers',
    description:
      'A miniature clay animation style featuring a floating object with bright, saturated, and playful colors.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ART_AND_DESIGN,
    brand: 'Google',
    tags: ['3d', 'claymation', 'stickers', 'playful', 'miniature'],
    presignedUrls: [`${localPath}3d-clay-stickers_template.png`],
    generationParameters: {
      prompt:
        'A miniature clay animation 3D floating [object with attributes] on a white background. The background is white. The colors are bright and saturated, and the overall look is playful. Everything in the scene is made of colorful clay.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '1:1',
      style: 'Modern',
      lighting: 'Studio Light',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: 'photorealistic, dark, gloomy',
      numMedia: 4,
    },
  },
  {
    id: 'enamel-pins',
    name: 'Enamel Pins',
    description:
      'Creates a stylish enamel pin with a gold border on a white background, perfect for custom merchandise mockups.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.FASHION_AND_APPAREL,
    brand: 'Google',
    tags: ['enamel pin', 'merchandise', 'mockup', 'gold border'],
    presignedUrls: [`${localPath}enamel-pins_template.png`],
    generationParameters: {
      prompt:
        'An enamel pin with a gold border on a white background. It features a [object with attributes]. Enamel pin on white background. It looks like a pin you might find on a jean jacket or backpack.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '1:1',
      style: 'Modern',
      lighting: 'Studio',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: 'shadows, realistic, human',
      numMedia: 4,
    },
  },
  {
    id: 'paper-craft',
    name: 'Paper Craft',
    description:
      'A construction paper craft depiction, made of textured pieces. Looks like an art student project.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ART_AND_DESIGN,
    brand: 'Google',
    tags: ['paper craft', 'construction paper', 'artistic', 'textured'],
    presignedUrls: [`${localPath}paper-craft_template.png`],
    generationParameters: {
      prompt:
        'A construction paper craft depicting a [object with attributes] on a white background. Made of pieces of textured construction paper pieces. It looks like something you would expect from an art student.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '1:1',
      style: 'Modern',
      lighting: 'Natural',
      colorAndTone: 'Pastel',
      composition: 'Closeup',
      negativePrompt: 'photorealistic, 3d, glossy',
      numMedia: 4,
    },
  },
  {
    id: 'stylized-portraits',
    name: 'Stylized Portraits',
    description:
      'Generates a close-up portrait in a graphic novel, vector art style with detailed subject descriptions.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ART_AND_DESIGN,
    brand: 'Google',
    tags: ['portrait', 'graphic novel', 'vector', 'character design'],
    presignedUrls: [`${localPath}stylized-portraits_template.png`],
    generationParameters: {
      prompt:
        'Close-up portrait. Graphic novel style. Vector art. [Subject]. [Profession/Role]. [Physical Traits]. [Clothing/Apparel Details]. [Activity/Action]. [Setting Details]. [Background Elements].',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '3:4',
      style: 'Sketch',
      lighting: 'Dramatic',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: 'photorealistic, blurry, deformed hands',
      numMedia: 4,
    },
  },
  {
    id: 'medieval-portraits',
    name: 'Medieval Portraits',
    description:
      'Creates a realistic, line art vector portrait in a medieval style on a clean white background.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ENTERTAINMENT,
    brand: 'Google',
    tags: ['medieval', 'portrait', 'line art', 'vector', 'historical'],
    presignedUrls: [`${localPath}medieval-portraits_template.png`],
    generationParameters: {
      prompt:
        'Line art, vector art. Portrait, realistic. White background. Medieval. [Role] [Physical Traits]. [Clothing]. [Facial Expression/Emotion]',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '3:4',
      style: 'Sketch',
      lighting: 'Natural',
      colorAndTone: 'Monochrome',
      composition: 'Closeup',
      negativePrompt: 'color, shading, 3d',
      numMedia: 4,
    },
  },
  {
    id: 'cake-maker',
    name: 'Cakemaker',
    description:
      'Designs a large sheet cake with a frosting drawing on top, shot from an overhead perspective.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.FOOD_AND_BEVERAGE,
    brand: 'Google',
    tags: ['cake', 'food', 'baking', 'frosting art', 'overhead shot'],
    presignedUrls: [`${localPath}cake-maker_template.png`],
    generationParameters: {
      prompt:
        'A large sheet cake on a gold foil cardboard with white frosting and decorative piping all around. The cake is on a white background, shot from overhead. On top of the cake there is a frosting drawing of [object with attributes].',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '4:3',
      style: 'Photorealistic',
      lighting: 'Studio',
      colorAndTone: 'Vibrant',
      composition: 'Shot from above',
      negativePrompt: 'dark, messy, out of frame',
      numMedia: 4,
    },
  },
  {
    id: 'anime-screenshot',
    name: 'Anime Screenshot',
    description:
      'Generates a crisp, 4k remastered still image from a fictional Japanese anime, capturing traditional cel animation.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ENTERTAINMENT,
    brand: 'Google',
    tags: ['anime', 'screenshot', 'cel animation', 'japanese', '4k'],
    presignedUrls: [`${localPath}anime-screenshot_template.png`],
    generationParameters: {
      prompt:
        'Still image from a Japanese anime remastered in 4k blu-ray. [description of the scene]. The still image is crisp, showing the traditional cel animation of a top rated animation.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '16:9',
      style: 'Fantasy',
      lighting: 'Cinematic',
      colorAndTone: 'Vibrant',
      composition: 'Landscape photography',
      negativePrompt: '3d, photorealistic, western cartoon',
      numMedia: 4,
    },
  },
  {
    id: 'road-sign-generator',
    name: 'Road Sign Generator',
    description:
      'Creates a custom road sign with a specific illustration, shape, and color background.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.OTHER,
    brand: 'Google',
    tags: ['road sign', 'signage', 'vector', 'illustration'],
    presignedUrls: [
      `${localPath}road-sign-generator_1_template.png`,
      `${localPath}road-sign-generator_2_template.png`,
    ],
    generationParameters: {
      prompt:
        'A road sign featuring an illustration of a [object with attributes]. The sign has a geometric shape with a solid color background. The sign is on a white background.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '1:1',
      style: 'Modern',
      lighting: 'Studio',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: 'photorealistic, shadows, 3d',
      numMedia: 4,
    },
  },
  {
    id: 'pixar-style-character',
    name: 'Pixar-Style Character',
    description:
      'Creates a tiny, fluffy, and cute baby animal in the style of Pixar, with huge soulful eyes and a vibrant environment.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ENTERTAINMENT,
    brand: 'Pixar',
    tags: ['pixar', '3d', 'character design', 'cute', 'animal'],
    presignedUrls: [`${localPath}pixar-style-character_template.png`],
    generationParameters: {
      prompt:
        'In style of Pixar, tiniest fluffiest cutest baby animal, huge soulful eyes , vibrant environment , the image is centered on a fluffy cute baby animal, magical sunrise light, 3D render . [Detailed description of animal and scene].',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '4:3',
      style: 'Fantasy',
      lighting: 'Golden Hour',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: '2d, drawing, dark, scary',
      numMedia: 4,
    },
  },
  {
    id: 'lego-construction',
    name: 'Lego Construction',
    description:
      'A Lego construction depicting a Lego object on a white background, made of colorful Lego blocks.',
    mimeType: MimeType.IMAGE,
    industry: IndustryEnum.ART_AND_DESIGN,
    brand: 'Lego',
    tags: ['lego', 'blocks', 'toy', 'construction', '3d'],
    presignedUrls: [`${localPath}lego-construction_template.png`],
    generationParameters: {
      prompt:
        'A Lego construction depicting a Lego [object with attributes] on a white background. Made of Lego blocks in different colors.',
      model: 'imagen-4.0-ultra-generate-preview-06-06',
      aspectRatio: '1:1',
      style: 'Realistic',
      lighting: 'Studio Light',
      colorAndTone: 'Vibrant',
      composition: 'Closeup',
      negativePrompt: 'photorealistic human, blurry, text',
      numMedia: 4,
    },
  },
];

// Automatically derive the list of unique industries from the templates
export const INDUSTRIES = [
  ...new Set(TEMPLATES.map(template => template.industry)),
].sort();
